session_name: Devenv-templated
windows:
  - window_name: Devenv-templated
    layout: main-vertical
    options:
      main-pane-width: 33%
    panes:
      - shell_command:
          - cd ~/Documents/Notes/Projects/devenv-templated
          # - nvim Notes.md ToDo.md
          - open-project
      - shell_command:
          - tmux resizep -y 90%
          - nvim
        focus: true
      - clear